In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import os
os.chdir('/content/gdrive/MyDrive/DDD')
os.getcwd() #查看當前路徑

'/content/gdrive/MyDrive/DDD'

In [ ]:
H5_path = '/content/gdrive/MyDrive/DDD/H5'
test_data_path = '/content/gdrive/MyDrive/DDD/test_data'

In [ ]:
import pickle
data_image = []

for i in range(10):
  print('{}%'.format(i*10))
  with open(test_data_path+'/image_data'+str(i)+'.pickle','rb') as f:
    data_image.extend(pickle.load(f))
    f.close()
print('100%')

0%
10%
20%
30%
40%
50%
60%
70%
80%
90%
100%


In [ ]:
len(data_image)

79726

In [ ]:
img_name = []
img_data = []


for name,feature in data_image:
  img_name.append(name)
  img_data.append(feature)

del data_image

In [ ]:
import numpy as np

# Converting images to nparray
img_data = np.array(img_data).reshape(-1,140,140,3)

print (img_data.shape)

(79726, 140, 140, 3)


In [ ]:
import tensorflow as tf

tf.__version__

'2.4.0'

#Xception imagenet randomly split

In [ ]:
from tensorflow.keras.models import load_model

model_a = load_model(H5_path+'/xception_imagenet_randomly_split.h5')
model_a.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Image_Input (InputLayer)     [(None, 140, 140, 3)]     0         
_________________________________________________________________
xception (Functional)        (None, 5, 5, 2048)        20861480  
_________________________________________________________________
flatten (Flatten)            (None, 51200)             0         
_________________________________________________________________
dense (Dense)                (None, 10)                512010    
Total params: 21,373,490
Trainable params: 21,318,962
Non-trainable params: 54,528
_________________________________________________________________


In [ ]:
prediction = model_a.predict(img_data)

In [ ]:
prediction[0]

array([6.8254160e-17, 9.7126320e-20, 7.2424010e-17, 1.9366944e-14,
       1.4640178e-13, 1.0000000e+00, 4.9747176e-18, 6.8168256e-18,
       1.6307622e-16, 7.8383180e-16], dtype=float32)

In [ ]:
len(prediction)

79726

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'img':img_name,
    'c0':[prediction[x][0] for x in range(len(prediction))],
    'c1':[prediction[x][1] for x in range(len(prediction))],
    'c2':[prediction[x][2] for x in range(len(prediction))],
    'c3':[prediction[x][3] for x in range(len(prediction))],
    'c4':[prediction[x][4] for x in range(len(prediction))],
    'c5':[prediction[x][5] for x in range(len(prediction))],
    'c6':[prediction[x][6] for x in range(len(prediction))],
    'c7':[prediction[x][7] for x in range(len(prediction))],
    'c8':[prediction[x][8] for x in range(len(prediction))],
    'c9':[prediction[x][9] for x in range(len(prediction))],
    })

In [ ]:
df

img            c0  ...            c8            c9
0           img_1.jpg  6.825416e-17  ...  1.630762e-16  7.838318e-16
1          img_10.jpg  5.538122e-21  ...  5.412677e-22  6.385346e-19
2         img_100.jpg  7.457302e-01  ...  2.111750e-02  4.981144e-03
3        img_1000.jpg  5.308121e-13  ...  9.999979e-01  2.132994e-06
4      img_100000.jpg  3.683923e-14  ...  1.593746e-15  5.650730e-15
...               ...           ...  ...           ...           ...
79721   img_99994.jpg  1.191550e-04  ...  7.813926e-06  1.021975e-06
79722   img_99995.jpg  2.790742e-10  ...  1.255382e-09  4.130836e-09
79723   img_99996.jpg  1.008966e-05  ...  1.627358e-04  6.180724e-06
79724   img_99998.jpg  2.542163e-12  ...  9.074604e-09  7.263269e-15
79725   img_99999.jpg  1.714426e-03  ...  1.736876e-02  3.462048e-03

[79726 rows x 11 columns]

In [ ]:
df.to_csv('submission.csv')

#InceptionV3 imagenet randomly split

In [ ]:
from tensorflow.keras.models import load_model

model = load_model(H5_path+'/inceptionV3_imagenet_randly_split.h5')
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Image_Input (InputLayer)     [(None, 140, 140, 3)]     0         
_________________________________________________________________
inception_v3 (Functional)    (None, 3, 3, 2048)        21802784  
_________________________________________________________________
flatten (Flatten)            (None, 18432)             0         
_________________________________________________________________
dense (Dense)                (None, 10)                184330    
Total params: 21,987,114
Trainable params: 21,952,682
Non-trainable params: 34,432
_________________________________________________________________


In [ ]:
prediction = model.predict(img_data)

In [ ]:
prediction[0]

array([4.5717599e-07, 2.9175792e-08, 3.0916908e-07, 3.3995855e-07,
       1.5007424e-05, 9.9997854e-01, 1.3127135e-07, 9.8523067e-08,
       3.6479466e-07, 4.6810219e-06], dtype=float32)

In [ ]:
len(prediction)

79726

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'img':img_name,
    'c0':[prediction[x][0] for x in range(len(prediction))],
    'c1':[prediction[x][1] for x in range(len(prediction))],
    'c2':[prediction[x][2] for x in range(len(prediction))],
    'c3':[prediction[x][3] for x in range(len(prediction))],
    'c4':[prediction[x][4] for x in range(len(prediction))],
    'c5':[prediction[x][5] for x in range(len(prediction))],
    'c6':[prediction[x][6] for x in range(len(prediction))],
    'c7':[prediction[x][7] for x in range(len(prediction))],
    'c8':[prediction[x][8] for x in range(len(prediction))],
    'c9':[prediction[x][9] for x in range(len(prediction))],
    })

In [ ]:
df.to_csv('submission_f.csv',index=False)

#Xception imagenet split on subject

In [ ]:
from tensorflow.keras.models import load_model

model = load_model(H5_path+'/xception_imagenet_split_on_subject.h5')
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Image_Input (InputLayer)     [(None, 140, 140, 3)]     0         
_________________________________________________________________
xception (Functional)        (None, 5, 5, 2048)        20861480  
_________________________________________________________________
flatten (Flatten)            (None, 51200)             0         
_________________________________________________________________
dense (Dense)                (None, 10)                512010    
Total params: 21,373,490
Trainable params: 21,318,962
Non-trainable params: 54,528
_________________________________________________________________


In [ ]:
prediction = model.predict(img_data)

In [ ]:
prediction[0]

array([1.0652469e-09, 7.4964923e-10, 1.8834193e-11, 5.8833904e-10,
       2.8504074e-08, 9.9999976e-01, 6.5402871e-11, 1.1545345e-08,
       5.8682081e-09, 2.9117305e-07], dtype=float32)

In [ ]:
len(prediction)

79726

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'img':img_name,
    'c0':[prediction[x][0] for x in range(len(prediction))],
    'c1':[prediction[x][1] for x in range(len(prediction))],
    'c2':[prediction[x][2] for x in range(len(prediction))],
    'c3':[prediction[x][3] for x in range(len(prediction))],
    'c4':[prediction[x][4] for x in range(len(prediction))],
    'c5':[prediction[x][5] for x in range(len(prediction))],
    'c6':[prediction[x][6] for x in range(len(prediction))],
    'c7':[prediction[x][7] for x in range(len(prediction))],
    'c8':[prediction[x][8] for x in range(len(prediction))],
    'c9':[prediction[x][9] for x in range(len(prediction))],
    })

In [ ]:
df.to_csv('submission_c.csv',index=False)

#InceptionV3 imagenet split on subject


In [ ]:
from tensorflow.keras.models import load_model

model = load_model(H5_path+'/inceptionV3_imagenet_split_on_subject.h5')
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Image_Input (InputLayer)     [(None, 140, 140, 3)]     0         
_________________________________________________________________
inception_v3 (Functional)    (None, 3, 3, 2048)        21802784  
_________________________________________________________________
flatten_1 (Flatten)          (None, 18432)             0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)                184330    
Total params: 21,987,114
Trainable params: 21,952,682
Non-trainable params: 34,432
_________________________________________________________________


In [ ]:
prediction = model.predict(img_data)
prediction[0]

array([4.7034018e-07, 5.8138799e-10, 7.4945206e-09, 2.0901902e-10,
       1.8192382e-09, 9.9999940e-01, 4.4911662e-08, 5.5162244e-09,
       2.4363619e-08, 6.4503539e-08], dtype=float32)

In [ ]:
len(prediction)

79726

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'img':img_name,
    'c0':[prediction[x][0] for x in range(len(prediction))],
    'c1':[prediction[x][1] for x in range(len(prediction))],
    'c2':[prediction[x][2] for x in range(len(prediction))],
    'c3':[prediction[x][3] for x in range(len(prediction))],
    'c4':[prediction[x][4] for x in range(len(prediction))],
    'c5':[prediction[x][5] for x in range(len(prediction))],
    'c6':[prediction[x][6] for x in range(len(prediction))],
    'c7':[prediction[x][7] for x in range(len(prediction))],
    'c8':[prediction[x][8] for x in range(len(prediction))],
    'c9':[prediction[x][9] for x in range(len(prediction))],
    })
df.to_csv('submission_d.csv',index=False)

#Xception Random split on subject

In [ ]:
from tensorflow.keras.models import load_model

model = load_model(H5_path+'/xception_random_initialization_split_on_subject.h5')
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Image_Input (InputLayer)     [(None, 140, 140, 3)]     0         
_________________________________________________________________
xception (Functional)        (None, 5, 5, 2048)        20861480  
_________________________________________________________________
flatten (Flatten)            (None, 51200)             0         
_________________________________________________________________
dense (Dense)                (None, 10)                512010    
Total params: 21,373,490
Trainable params: 21,318,962
Non-trainable params: 54,528
_________________________________________________________________


In [ ]:
prediction = model.predict(img_data)
prediction[0]

array([2.3318634e-04, 4.9037725e-04, 7.2192303e-03, 2.7758260e-03,
       5.1088881e-04, 9.7682434e-01, 9.8394731e-04, 7.9262936e-03,
       1.4735687e-04, 2.8885405e-03], dtype=float32)

In [ ]:
len(prediction)

79726

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'img':img_name,
    'c0':[prediction[x][0] for x in range(len(prediction))],
    'c1':[prediction[x][1] for x in range(len(prediction))],
    'c2':[prediction[x][2] for x in range(len(prediction))],
    'c3':[prediction[x][3] for x in range(len(prediction))],
    'c4':[prediction[x][4] for x in range(len(prediction))],
    'c5':[prediction[x][5] for x in range(len(prediction))],
    'c6':[prediction[x][6] for x in range(len(prediction))],
    'c7':[prediction[x][7] for x in range(len(prediction))],
    'c8':[prediction[x][8] for x in range(len(prediction))],
    'c9':[prediction[x][9] for x in range(len(prediction))],
    })
df.to_csv('submission_a.csv',index=False)

#InceptionV3 Random split on subject

In [ ]:
from tensorflow.keras.models import load_model

model = load_model(H5_path+'/inceptionV3_random_initialization_split_on_subject.h5')
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Image_Input (InputLayer)     [(None, 140, 140, 3)]     0         
_________________________________________________________________
inception_v3 (Functional)    (None, 3, 3, 2048)        21802784  
_________________________________________________________________
flatten (Flatten)            (None, 18432)             0         
_________________________________________________________________
dense (Dense)                (None, 10)                184330    
Total params: 21,987,114
Trainable params: 21,952,682
Non-trainable params: 34,432
_________________________________________________________________


In [ ]:
prediction = model.predict(img_data)
prediction[0]

array([6.9703710e-06, 2.2570846e-07, 2.0104682e-05, 7.0223774e-07,
       6.1020609e-07, 7.7495128e-01, 2.0212124e-07, 2.5607497e-04,
       1.2539711e-04, 2.2463845e-01], dtype=float32)

In [ ]:
len(prediction)

79726

In [ ]:
import pandas as pd
df = pd.DataFrame({
    'img':img_name,
    'c0':[prediction[x][0] for x in range(len(prediction))],
    'c1':[prediction[x][1] for x in range(len(prediction))],
    'c2':[prediction[x][2] for x in range(len(prediction))],
    'c3':[prediction[x][3] for x in range(len(prediction))],
    'c4':[prediction[x][4] for x in range(len(prediction))],
    'c5':[prediction[x][5] for x in range(len(prediction))],
    'c6':[prediction[x][6] for x in range(len(prediction))],
    'c7':[prediction[x][7] for x in range(len(prediction))],
    'c8':[prediction[x][8] for x in range(len(prediction))],
    'c9':[prediction[x][9] for x in range(len(prediction))],
    })
df.to_csv('submission_b.csv',index=False)